---
- debug:
    msg: "Performing installation of Artifactory version : {{ artifactory_version }} "

- name: install nginx
  include_role:
    name: artifactory_nginx
  when: artifactory_nginx_ssl_enabled == false

- name: install nginx with SSL
  include_role:
    name: artifactory_nginx_ssl
  when: artifactory_nginx_ssl_enabled == true

- name: Ensure group artifactory exist
  become: yes
  group:
    name: "{{ artifactory_group }}"
    gid: "{{ artifactory_gid }}"
    state: present

- name: Ensure user artifactory exist
  become: yes
  user:
    uid: "{{ artifactory_uid }}"
    name: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    create_home: yes
    home: "{{ artifactory_home }}"
    shell: /bin/bash
    state: present

- name: Download artifactory
  become: yes
  unarchive:
    src: "{{ artifactory_tar }}"
    dest: "{{ jfrog_home_directory }}"
    remote_src: yes
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    creates: "{{ artifactory_untar_home }}"
  when: artifactory_tar is defined
  register: downloadartifactory
  until: downloadartifactory is succeeded
  retries: 3

- name: Check if app directory exists
  become: yes
  stat:
    path: "{{ artifactory_home }}/app"
  register: app_dir_check

- name: Copy untar directory to artifactory home
  become: yes
  command: "cp -r {{ artifactory_untar_home }}/. {{ artifactory_home }}"
  when: not app_dir_check.stat.exists

- name: Create required directories 
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
  loop:
    - "{{ artifactory_file_store_dir }}"
    - "{{ artifactory_home }}/var/data"
    - "{{ artifactory_home }}/var/etc"
    - "{{ artifactory_home }}/var/etc/security/"
    - "{{ artifactory_home }}/var/etc/artifactory/info/"

- name: Configure systemyaml
  become: yes
  template:
    src: "{{ artifactory_system_yaml_template }}"
    dest: "{{ artifactory_home }}/var/etc/system.yaml"
  notify: restart artifactory

- name: Configure master key
  become: yes
  copy:
    dest: "{{ artifactory_home }}/var/etc/security/master.key"
    content: |
      {{ master_key }}
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0640

- name: Configure join key
  become: yes
  copy:
    dest: "{{ artifactory_home }}/var/etc/security/join.key"
    content: |
      {{ join_key }}
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0640
  notify: restart artifactory

- name: Configure installer info
  become: yes
  template:
    src: installer-info.json.j2
    dest: "{{ artifactory_home }}/var/etc/artifactory/info/installer-info.json"
  notify: restart artifactory

- name: Configure binary store
  become: yes
  template:
    src: binarystore.xml.j2
    dest: "{{ artifactory_home }}/var/etc/artifactory/binarystore.xml"
  notify: restart artifactory

- name: Configure single license
  become: yes
  template:
    src: artifactory.lic.j2
    dest: "{{ artifactory_home }}/var/etc/artifactory/artifactory.lic"
  when: artifactory_single_license is defined
  notify: restart artifactory

- name: Configure HA licenses 
  become: yes
  template:
    src: artifactory.cluster.license.j2
    dest: "{{ artifactory_home }}/var/etc/artifactory/artifactory.cluster.license"
  when: artifactory_licenses is defined
  notify: restart artifactory

- name: Download database driver
  become: yes
  get_url:
    url: "{{ postgres_driver_download_url }}"
    dest: "{{ artifactory_home }}/var/bootstrap/artifactory/tomcat/lib"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
  when: postgres_driver_download_url is defined
  notify: restart artifactory

- name: Create artifactory service
  become: yes
  shell: "{{ artifactory_home }}/app/bin/installService.sh"
  
- name: Ensure permissions are correct
  become: yes
  file:
    path: "{{ jfrog_home_directory }}"
    group: "{{ artifactory_group }}"
    owner: "{{ artifactory_user }}"
    recurse: yes

- name: Restart artifactory
  meta: flush_handlers

- name : Wait for artifactory to be fully deployed  
  uri: url=http://127.0.0.1:8082/router/api/v1/system/health timeout=130
  register: result
  until: result.status == 200
  retries: 25
  delay: 5
