---
- name: install acl, python3-psycopg2
  become: yes
  apt:
    name:
      - acl
      - python3-psycopg2
    state: present
    update_cache: yes
  ignore_errors: yes

- name: add postgres apt key
  become: yes
  apt_key:
    url: "{{ postgres_apt_key_url }}"
    id: "{{ postgres_apt_key_id }}"
    validate_certs: no
    state: present

- name: register APT repository
  become: yes
  apt_repository:
    repo: "{{ postgres_apt_repository_repo }}"
    state: present
    filename: pgdg

- name: install postgres packages
  become: yes
  apt:
    name:
      - postgresql-{{ postgres_version }}
      - postgresql-contrib-{{ postgres_version }}
    state: present
