---

- name: install EPEL repository
  become: yes
  yum: name=epel-release state=present
  when: >  # not for Fedora
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Red Hat Enterprise Linux'

- name: install acl
  become: yes
  yum:
    name:
      - acl
      - sudo
      - wget
      - perl
    state: present
  ignore_errors: yes

- name: install python3-psycopg2
  become: yes
  yum:
    name:
      - python3-psycopg2
    state: present
  when: ansible_distribution_major_version == '8'

- name: install python2-psycopg2
  become: yes
  yum:
    name:
      - python-psycopg2
    state: present
  when: ansible_distribution_major_version == '7'

- name: fixup some locale issues
  become: yes
  lineinfile:
    dest: /etc/default/locale
    line: 'LANGUAGE="{{ item }}"'
    state: present
    create: yes
  loop:
    - 'en_US:en'
    - 'en_us.UTF-8'

- name: get latest version
  vars:
    base: http://download.postgresql.org/pub/repos/yum
    ver: "{{ ansible_distribution_major_version }}"
  shell: |
    set -eo pipefail
    wget -O - {{ base }}/reporpms/EL-{{ ver }}-x86_64/ 2>/dev/null | \
    grep 'pgdg-redhat-repo-latest' | \
    perl -pe 's/^.*rpm">//g' | \
    perl -pe 's/<\/a>.*//g' | \
    tail -n 1
  args:
    executable: /bin/bash
  changed_when: false
  check_mode: false
  register: latest_version
  tags: [skip_ansible_lint]

- name: config postgres repository
  become: yes
  vars:
    base: http://download.postgresql.org/pub/repos/yum
    ver: "{{ ansible_distribution_major_version }}"
  yum:
    name: "{{ base }}/reporpms/EL-{{ ver }}-x86_64/{{ latest_version.stdout }}"
    state: present

- name: install postgres packages
  become: yes
  yum:
    name:
      - postgresql{{ postgres_server_pkg_version }}-server
      - postgresql{{ postgres_server_pkg_version }}-contrib
    state: present