---
- hosts: postgres-servers
  collections:
    - jfrog.platform
  roles:
    - postgres

- hosts: artifactory-servers
  collections:
    - jfrog.platform
  roles:
    - artifactory

- hosts: xray-servers
  collections:
    - jfrog.platform
  roles:
    - xray