---
- hosts: postgres_servers
  collections:
    - jfrog.platform
  roles:
    - postgres

- hosts: artifactory_servers
  collections:
    - jfrog.platform
  roles:
    - artifactory

- hosts: xray_servers
  collections:
    - jfrog.platform
  roles:
    - xray

- hosts: distribution_servers
  collections:
    - jfrog.platform
  roles:
    - distribution

- hosts: missioncontrol_servers
  collections:
    - jfrog.platform
  roles:
    - missioncontrol
