- name: Check rabbitmq cluster_keepalive_interval option
  become: yes
  ignore_errors: yes
  shell: |
    ./rabbitmqctl --erlang-cookie {{ xray_rabbitmq_default_cookie }} eval \
        'application:get_env(rabbit, cluster_keepalive_interval).' \
        | tr -d '}{' | cut -d ',' -f2
  args:
    chdir: "{{ xray_home }}/app/third-party/rabbitmq/sbin/"
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  register: cluster_keepalive_interval_value

- name: Check rabbitmq handshake_timeout option
  become: yes
  ignore_errors: yes
  shell: |
    ./rabbitmqctl --erlang-cookie {{ xray_rabbitmq_default_cookie }} eval \
        'application:get_env(rabbit, handshake_timeout).' \
        | tr -d '}{' | cut -d ',' -f2
  args:
    chdir: "{{ xray_home }}/app/third-party/rabbitmq/sbin/"
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  register: handshake_timeout_value

- name: Check rabbitmq vm_memory_high_watermark.relative option
  become: yes
  ignore_errors: yes
  shell: |
    ./rabbitmqctl --erlang-cookie {{ xray_rabbitmq_default_cookie }} eval \
        'application:get_env(rabbit, vm_memory_high_watermark).' \
        | tr -d '}{' | cut -d ',' -f2
  args:
    chdir: "{{ xray_home }}/app/third-party/rabbitmq/sbin/"
  environment:
    LC_ALL: en_US.UTF-8
    LC_CTYPE: en_US.UTF-8
  register: vm_memory_high_watermark_relative_value

- name: Store result
  include_role:
    name: report
  vars:
    stop_testing_if_fail: false
    test_description: "{{ test_ext_description }}Check rabbitmq custom options values. INST-775"
    test_host: "{{ inventory_hostname }}"
    test_result: >-
        {{
            vm_memory_high_watermark_relative_value.stdout == rabbitmq_custom_values['vm_memory_high_watermark']
            and cluster_keepalive_interval_value.stdout == rabbitmq_custom_values['cluster_keepalive_interval']
            and handshake_timeout_value.stdout == rabbitmq_custom_values['handshake_timeout']
        }}
    report_action: "store-result"
    log_result: >-
        {{
            {}
            | combine({'handshake_timeout': {'real': handshake_timeout_value.stdout, 'expected': rabbitmq_custom_values.handshake_timeout}})
            | combine({'vm_memory_high_watermark': {'real': vm_memory_high_watermark_relative_value.stdout, 'expected': rabbitmq_custom_values.vm_memory_high_watermark}})
            | combine({'cluster_keepalive_interval': {'real': cluster_keepalive_interval_value.stdout, 'expected': rabbitmq_custom_values.cluster_keepalive_interval}})
        }}
